name: test
on: [push,pull_request]
jobs:
  xenial:
    container: 
      image: swift:5.4-xenial
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: swift test  --sanitize=thread
  bionic:
    container: 
      image: swift:5.4-bionic
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: swift test  --sanitize=thread
  run_test:
    container: 
      image: swift:5.4
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up swift
      uses: fwal/setup-swift@v1
    - name: Get swift vision
      run: swift --version
