name: test
on: [push,pull_request]
jobs:
  xenial:
    container: 
      image: swift:5.4-xenial
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: swift test  --sanitize=thread

  bionic:
    container: 
      image: swift:5.4-bionic
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: swift test  --sanitize=thread

  run_test_on_MacOS_BigSur:
    container: 
      image: swift:5.4
    runs-on: macOS-11
    steps:
    - uses: actions/checkout@v1
    - name: run_test_file
      run: swift test --sanitize=thread 

  run_test_on_MacOS_lastest:
    container: 
      image: swift:5.4
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: run_test_file
      run: swift test --sanitize=thread 
  