name: test
on: [push,pull_request,release]
jobs:
  xenial:
    container: 
      image: swift:5.4-xenial
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: swift test  --sanitize=thread

  bionic:
    container: 
      image: swift:5.4-bionic
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: swift test  --sanitize=thread

  run_test_on-swift-5-4:
    container: 
      image: swift:5.4-bionic
    runs-on: ubuntu-latest
    steps:
    - uses: fwal/setup-swift@v1
      with:
        swift-version: "5.4.0"

    - uses: actions/checkout@v1
    - run: swift test  --sanitize=thread

 