name: test
on: [push,pull_request,release]
jobs:
  xenial:
    container: 
      image: swift:5.4-xenial
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: swift test  --sanitize=thread

  bionic:
    container: 
      image: swift:5.4-bionic
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: swift test  --sanitize=thread

  run_test_on-swift-5-3:
    container: 
      image: swift:5.3-bionic
    runs-on: ubuntu-latest
    steps:
    - uses: fwal/setup-swift@v1
      with:
        swift-version: "5.3.0"

    - uses: actions/checkout@v1
    - run: swift test  --sanitize=thread

  run_test_on-swift-5-2:
    container: 
      image: swift:5.2-bionic
    runs-on: ubuntu-latest
    steps:
    - uses: fwal/setup-swift@v1
      with:
        swift-version: "5.2.0"

    - uses: actions/checkout@v1
    - run: swift test  --sanitize=thread

  run_test_on-swift-5-1:
    container: 
      image: swift:5.1-bionic
    runs-on: ubuntu-latest
    steps:
    - uses: fwal/setup-swift@v1
      with:
        swift-version: "5.1.0"

    - uses: actions/checkout@v1
    - run: swift test  --sanitize=thread

  run_test_on-swift-5-0:
    container: 
      image: swift:5.0-bionic
    runs-on: ubuntu-latest
    steps:
    - uses: fwal/setup-swift@v1
      with:
        swift-version: "5.0.0"

    - uses: actions/checkout@v1
    - run: swift test  --sanitize=thread


  